### ISSUE TITLE
Support Error.prepareStackTrace

### ISSUE THREAD

**Issue by dmail** [evanw/node-source-map-support#101]
Can you confirm that since error.stack is not lazy anymore the main purpose of this module is broken because it rely on Error.prepareStacktrace to transform error.stack (see https://github.com/evanw/node-source-map-support/blob/master/source-map-support.js#L400) ?

**Comment by ncalexan** [comment]
It looks like this is the case: https://github.com/nodejs/node-v0.x-archive/issues/5478.

That suggests we need to do something else entirely to print meaningful stack traces.

**Comment by LinusU** [comment]
Please feel free to reopen if this is still relevant...
