### ISSUE TITLE
Problems with isInBrowser() and jsdom

### ISSUE THREAD

**Issue by asgerhallas** [evanw/node-source-map-support#102]
I use jsdom for testing some jQuery functionality using node and when installing source-map-support, I get the problem, that the isInBrowser() function returns true, though I'm really only faking it. And then it can't load the source maps.

I have two suggestions for fixing this: 

1. Only check for browser-capabilities on construction and let isInBrowser be constant. That way I could simply just install jsdom after source-map-support. And I can't think of any other way isInBrowser could change from call to call.

2. Make an option on install to force either node or browser behavior.

I would be happy to make a PR if any of the above solutions seems ok to you :)

And great project by the way!

**Comment by julien-f** [comment]
There will always be edge cases so I much prefer the second option :)

**Comment by asgerhallas** [comment]
Perfect. I'll get on it! :)

**Comment by electricmonk** [comment]
+1

**Comment by tugend** [comment]
Hi, I tried to make a pull request to solve the issue.
Then I tried to make another (different strategy, pick what you'd prefer).

https://github.com/evanw/node-source-map-support/pull/106
https://github.com/evanw/node-source-map-support/pull/105

Unfortunately there's a build error concerning some whitespace which I really don't get looking at my changes. =/

**Comment by asgerhallas** [comment]
@julien-f sorry, I got caught up in some other tasks, so @tugend got it done...

@tugend none of those seem to implement option 2?

**Comment by asgerhallas** [comment]
@tugend maybe it would be more intuitive to have an environment option that could have the value 'node' | 'browser' | 'auto', with auto as default (as now) and the just forcing the chosen environment.

**Comment by tugend** [comment]
@asgerhallas good point. Hereby updated https://github.com/evanw/node-source-map-support/pull/105/files

**Comment by tugend** [comment]
To avoid confusion I removed my alternative and only kept the pull request for specifying the environment as an option. Sorry for confusion. I updated the docs to account. I did not find any existing tests for options and could not run the tests on my machine (possible a win10 issue?). The module it self works fine.

**Comment by tugend** [comment]
@julien-f, hey friend, we're a couple of people who could use the feature in 106.

If you wouldn't mind having a look at https://github.com/evanw/node-source-map-support/pull/106, 
we'd be much obliged. 

I have no idea why Travis is failing #62.1NodeJs:IOjs handleUncaughtExceptions, it seems to be some encoding (everything is utf-8) or a whitespace issue, but I haven't been able to figure it out. =(/

If there is something I can improve on the pullrequest please don't hesitate to let me know.

Cheers

**Comment by electricmonk** [comment]
Awesome. @julien-f - when can we expect a release?

**Comment by julien-f** [comment]
@electricmonk Published as v0.3.3, let me know if there are any issues.
