### ISSUE TITLE
use -r when using in node

### ISSUE THREAD

**Issue by apechimp** [evanw/node-source-map-support#113]
Another method (as of [io.js 2.2.0](https://github.com/nodejs/node/blob/master/CHANGELOG.md#2015-05-31-version-220-rvagg)) is to use the `-r` flag in node, e.g., `node -r source-map-support/register foo.js` which will remove the need to modify compiled code.

**Comment by LinusU** [comment]
That is very nice! We should add it to the readme :)

**Comment by apechimp** [comment]
Cool. I'll draft a PR :smile_cat:
