### ISSUE TITLE
NPM keeps re-installing source-map-support

### ISSUE THREAD

**Issue by rogierschouten** [evanw/node-source-map-support#115]
Every time I run npm install, source-map-support gets re-installed even though it was already there. I've seen it on multiple PCs now. This issue does not occur with any other module so I guess it must be something specific to source-map-support.

Seen under Windows 7 with NPM 2.14.7  (installed with Node.JS 4.2.1)

```
> npm install
source-map-support@0.3.3 node_modules\source-map-support
â””â”€â”€ source-map@0.1.32 (amdefine@1.0.0)

> npm install
source-map-support@0.3.3 node_modules\source-map-support
â””â”€â”€ source-map@0.1.32 (amdefine@1.0.0)
```

**Comment by LinusU** [comment]
How does your package.json look?

**Comment by rogierschouten** [comment]
Honestly you don't want to know. On the other hand, I just tried to reproduce with a package.json with only source-map-support and that doesn't show the problem. I'll see if I can binary-search what the problem is.

**Comment by rogierschouten** [comment]
Found it. source-map-support was listed with a github link because we were waiting for you to npm publish something. By now we can use "^0.3.3" again. Apparently the line below causes npm to reinstall every time.

```
    "source-map-support": "evanw/node-source-map-support",
```
