### ISSUE TITLE
Running mocha through babel

### ISSUE THREAD

**Issue by markelog** [evanw/node-source-map-support#135]
Hi there.

Trying to run tests through babel with following config - 

```js
{
  "presets": ["es2015"],
  "sourceMaps": "inline" // or true
}
```

on following test (path `tests/test.js`)
```js
import path from 'path'; // just an example

describe('test', () => {
	it('test', () => {
		throw new Error('test');
	});
});
```

with command `mocha --compilers js:babel-register --require source-map-support/register tests` it gives this output  -
```
  1) test test:
     Error: test
      at Context.<anonymous> (tests/test.js:11:9)
```
Which is clearly wrong. 

But if i do `babel -d test tests --source-maps` and `mocha --require source-map-support/register`. Output is correct.

This is not a stackoveflow, but i think if we would document the correct answer it would be beneficial for the users.

Thank you

**Comment by alexgorbatchev** [comment]
I'm also seeing strange results, where the code line is displayed from the transpiled file, yet the filename and line number point to the correct source file.

**Comment by mucsi96** [comment]
@markelog I had similar issue. And I could solve it with
- I removed `"sourceMaps": "inline"` from `.babelrc`
- I removed the `--require source-map-support/register`

source-map-support is now handled inside babel-register

I hope this help

**Comment by graingert** [comment]
@mucsi96 where is this documented?

**Comment by LinusU** [comment]
It's added to our readme now 👍
