### ISSUE TITLE
Bumping source-map?

### ISSUE THREAD

**Issue by TheSavior** [evanw/node-source-map-support#141]
It looks like source-map-support has a dependency on source-map @ 0.1.32 created in September 2014. The current version is 0.5.6. Is there any reason we need to stay on such an old version. We are seeing a flake from inside of source-map  via this library via karma-source-map-support and it is really hard to track down the error since we are on such an old version. 

For reference of the underlying flake we are having trouble tracking down: https://github.com/sinonjs/sinon/issues/1094

**Comment by LinusU** [comment]
If anyone would like to scan thru the changelog and see if there any breaking changes we should be aware of, that would be much appreciated. I'm okay with bumping the dependency if it looks good

**Comment by seanpoulter** [comment]
source-map was updated in fd4c649209915ab8f4785ceb97bcb9998b22711 to version **0.5.3**.
The Mocha tests pass bumping to **0.5.6**. I can submit the PR if it's easier for you to confirm @LinusU.

**Comment by LinusU** [comment]
I would love that 👍
