### ISSUE TITLE
Update .npmignore.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [evanw/node-source-map-support#157]
Right now it's ignoring `browserify-test`, but not `amd-test`, `browser-test`, or `header-test`.  Alternatively, you could add `files` to `package.json` and just whitelist the files you need.  I would be happy to submit a PR either way.

**Comment by LinusU** [comment]
I would be happy to accept a pr. Personally leaning towards updating npmignore...

**Comment by wtgtybhertgeghgtwtg** [comment]
PR in #158.
