### ISSUE TITLE
Error trying to load the source map URL from a library hosted on a different domain

### ISSUE THREAD

**Issue by alonsogarciapablo** [evanw/node-source-map-support#161]
We're using this library in combination with `jasmine` and we haven't had any problems so far. We now need to import the Google Maps API JS library in our `SpecRunner.html`, and that's causing some problems.

Basically, when there's an error inside the Google Maps API library, `node-source-map-support` tries to load the source map URL for the library ([here](https://github.com/evanw/node-source-map-support/blob/313c03883ec48dd99cdf43fc9457d40d9599c142/source-map-support.js#L100)), which is obviously not hosted on the same domains as our local `SpecRunner.html` (which is served from `http://localhost:9001`).

This is triggering the following error in Chrome:

```
XMLHttpRequest cannot load http://maps.googleapis.com/maps/api/js?key=API_KEY.
No 'Access-Control-Allow-Origin' header is present on the requested resource.
Origin 'http://localhost:9001' is therefore not allowed access.
```

Perhaps we could wrap [this whole block](https://github.com/evanw/node-source-map-support/blob/313c03883ec48dd99cdf43fc9457d40d9599c142/source-map-support.js#L98-L108) with a `try { ... } catch (..) { ... }` as you guys are doing [here](https://github.com/evanw/node-source-map-support/blob/313c03883ec48dd99cdf43fc9457d40d9599c142/source-map-support.js#L61-L79).

**Comment by thenickofnicks** [comment]
+1

**Comment by thenickofnicks** [comment]
Can we re-evaluate this pull request.  The failed tests may pass now that eval was fixed for node 7. @evanw.

**Comment by thenickofnicks** [comment]
I created a new pull request #169.  All tests pass.

**Comment by LinusU** [comment]
Thank you, released as v0.4.11

**Comment by thenickofnicks** [comment]
One issue I didn't notice though.. the browser file needed to be rebuilt manually for the repo to reflect the changes.  Here is a new pull request for that. #170

**Comment by LinusU** [comment]
Should have been done here: https://github.com/evanw/node-source-map-support/commit/cc883dd388740682669713fc5668fb454774de70

👌
