### ISSUE TITLE
native%20array.js 404 (Not Found)

### ISSUE THREAD

**Issue by uiteoi** [evanw/node-source-map-support#164]
index.html:
```
  <script src="/lib/browser-source-map-support.js.min" type="text/javascript"></script>
  <script>sourceMapSupport.install();</script>
```
Using latest Chrome I get two errors ```"native%20array.js 404 (Not Found)"``` line 81 and 82 in
```"browser-source-map-support.js.min"``` after accessing the first Error stack trace.

Chrome dev tools network panel shows the following network request:
```GET /native%20array.js HTTP/1.1```

I have checked all source maps associated with javascript assets on this page, without finding any reference for any file name ending with ```"array.js"```.

Thanks for the great library.

**Comment by jonyeezs** [comment]
I'm getting this error as well. This only happens in browser

this PR #130 should have fixed it i thought, but it looks like it is still happening.

This is the error i'm getting:
```
21 12 2016 14:56:48.454:WARN [proxy]: failed to proxy /__karma__/native%20array.js (socket hang up)
21 12 2016 14:56:48.454:WARN [proxy]: failed to proxy /__karma__/native%20array.js (socket hang up)
21 12 2016 14:56:48.455:WARN [proxy]: failed to proxy /__karma__/native%20array.js (socket hang up)
21 12 2016 14:56:48.455:WARN [proxy]: failed to proxy /__karma__/native%20array.js (socket hang up)
21 12 2016 14:56:48.456:WARN [proxy]: failed to proxy /__karma__/native%20array.js (socket hang up)
21 12 2016 14:56:48.456:WARN [proxy]: failed to proxy /__karma__/native%20array.js (socket hang up)
Chrome 54.0.2840 (Windows 8.1 0.0.0) ERROR
  Uncaught NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://localhost:9876/__karma__/native%20array.js'.
  at http://localhost:9876/__karma__node_modules/source-map-support/browser-source-map-support.js:82
```

**Comment by jonyeezs** [comment]
I tried skipping the http requests (there looks to be two places where it makes the calls), but still get requests...I've no idea what's going on here.

**Comment by LinusU** [comment]
Should be fixed now 👌

**Comment by uiteoi** [comment]
I confirm that the fix works, thanks for the quick fix :)
