### ISSUE TITLE
please publish 0.4.11 to npm

### ISSUE THREAD

**Issue by jasonswearingen** [evanw/node-source-map-support#172]
latest npm version is 0.4.10m  and I am suffering the Access Control Allow Origin issue as mentioned here: https://github.com/evanw/node-source-map-support/issues/161 , fixed in 0.4.11

**Comment by LinusU** [comment]
Hehe, sorry about that :)

It should be published now 👌

**Comment by jasonswearingen** [comment]
ok thank you, got it, and I can confirm that it fixes the issue mentioned in #161
