### ISSUE TITLE
Using `console.trace` with value outputs `[object Object]`

### ISSUE THREAD

**Issue by blakeembrey** [evanw/node-source-map-support#195]
From https://github.com/TypeStrong/ts-node/issues/441. I quickly narrowed it down to this module as I can disable source map support and the output becomes correct - mirroring node.js functionality. Reproduction from `ts-node`:

```ts
console.trace('a');
```

```
[object Object]
    at Object.<anonymous> (/Users/blakeembrey/Projects/tmp/t.ts:1:9)
    at Module._compile (module.js:573:30)
    at Module.m._compile (/Users/blakeembrey/Projects/GitHub/TypeStrong/ts-node/src/index.ts:413:23)
    at Module._extensions..js (module.js:584:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/blakeembrey/Projects/GitHub/TypeStrong/ts-node/src/index.ts:416:12)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at Object.<anonymous> (/Users/blakeembrey/Projects/GitHub/TypeStrong/ts-node/src/_bin.ts:177:12)
```

**Comment by LinusU** [comment]
Hmm, this is bad. I don't think I'll have time in the nearest few days to look at this, so would be happy to accept a PR!

**Comment by ddanila** [comment]
Not sure if this information will be helpful, but I made some investigations and it works for me with node.js <= 8.1.4 and broken in node.js =>8.2.0 with same (latest stable) ts-node package.

**Comment by dboune** [comment]
For whatever reason in some iteration through `prepareStackTrace` the `error` parameter is provided a plain object with the following structure:

```
{
  name: 'Trace',
  message: 'Error message',
  stack: '...'
}
```

Thus when `.toString()` is called on the error the result is '[object Object]'.

I do not know if this is the best way to resolve the problem, but I was able to resolve it for myself by modifying `prepareStackTrace` as follows:

```js
function prepareStackTrace(error, stack) {
  if (emptyCacheBetweenOperations) {
    fileContentsCache = {};
    sourceMapCache = {};
  }

  var message = (error instanceof Error) ? error : error.message;

  return message + stack.map(function(frame) {
    return '\n    at ' + wrapCallSite(frame);
  }).join('');

}
```

Alternatively, being direct using `error.message + stack.map(...` also seemed to work. I'm making an assumption here either way that the message property will always exist, and it very well may for this case.

**Comment by RDeluxe** [comment]
Any news about this ?

**Comment by hiro5id** [comment]
bump...

**Comment by Somebi** [comment]
Bug is still there... using v11.3.0

**Comment by legraphista** [comment]
Any updates? This is still an issue.
`console.trace` and `Error.captureStackTrace` are broken.

**Comment by Somebi** [comment]
bump, still not working

**Comment by SystemDisc** [comment]
This is still broken
