### ISSUE TITLE
Error stack not always printed to console on uncaught error

### ISSUE THREAD

**Issue by Hilzu** [evanw/node-source-map-support#207]
The `uncaughtException` handler that source-map-support installs prints the error and immediately exits:
https://github.com/evanw/node-source-map-support/blob/9034a03435e70b35e7dc99685b78779bcdaa2dca/source-map-support.js#L436-L437

The Node.js `process.exit` documentation explains why this is a bad idea: https://nodejs.org/api/process.html#process_process_exit_code

> The reason this is problematic is because writes to process.stdout in Node.js are sometimes asynchronous and may occur over multiple ticks of the Node.js event loop. Calling process.exit(), however, forces the process to exit before those additional writes to stdout can be performed.

This means that in some cases the Node process doesn't print any output when crashing because of an uncaught exception. The correct way to do this is to set the `process.exitCode` property to `1` instead of immediately exiting as explained in the docs. I can open a PR with this change if you prefer that.

**Comment by LinusU** [comment]
Hmm, we could potentially replace that with [`fs.writeSync(2, error.stack)`](https://nodejs.org/api/fs.html#fs_fs_writesync_fd_string_position_encoding)

PRs welcome 🙌
