### ISSUE TITLE
Error from tsx component (Create-React-App with Typescript project)

### ISSUE THREAD

**Issue by abobykin** [evanw/node-source-map-support#221]
Trying to setup working source maps in my project (node-sass-chokidar package)

The error is: react-typescript/src/App.tsx
(5,1): require statement not part of an import statement

Here is my component (below) where I wrote this two lines from the doc (but with adding the type 'any at the end of the first'):
declare function require(name: string): any;
require('source-map-support').install();

My component:

import * as React from 'react';
import './App.css';
import Dashboard from './components/dashboard/dashboard';

declare function require(name: string): any;
require('source-map-support').install();

class App extends React.Component {
  public render() {
    return (
      <Dashboard name={'Alex'}/>
    );
  }
}

export default App;

Could you please tell me, is it possible with your package, thanks in advance! ?

**Comment by LinusU** [comment]
What is it that is giving you this error?

> (5,1): require statement not part of an import statement

Anyhow, if you are using TypeScript I think that you should do it like this:

```typescript
import SourceMapSupport = require('source-map-support')

SourceMapSupport.install()

// ...
```

Also, instead of doing this programmatically you can do this using the Node.js CLI, which might be a better fit:

```sh
node -r source-map-support/register foobar.js
```

**Comment by abobykin** [comment]
Sorry for such a delay, just closing what was opened long ago @LinusU 

Thank you! :)
