### ISSUE TITLE
Using source-map-support with typescript

### ISSUE THREAD

**Issue by josecolella** [evanw/node-source-map-support#225]
Hello this is more of a general question than anything. I'm using source-map-support with typescript in the following manner:

> node -r source-map-support/register ./dist/server.bundle.js

where the server.bundle.js is a bundle generated by webpack. Is this the correct way to use source map support with typescript and webpack?

**Comment by LinusU** [comment]
Do you also have a `./dist/server.bundle.js.map` file? In that case, yes

**Comment by josecolella** [comment]
@LinusU Correct, a `.js.map` file is also generated from webpack. Thanks for your response.
