### ISSUE TITLE
Wrong stack trace with webpack

### ISSUE THREAD

**Issue by demian85** [evanw/node-source-map-support#238]
I'm getting this:
```
TypeError: Cannot read property 'length' of undefined
    at t.handler (/var/task/webpack:/src/main.ts:16:38)
    at invoke (/var/runtime/node_modules/awslambda/index.js:285:5)
    at InvokeManager.start (/var/runtime/node_modules/awslambda/index.js:151:9)
```

I think the `webpack:` part should not be there.

**Comment by morgs32** [comment]
Could this have to do with the webpack generated sourcemap?

**Comment by buaazhangfan** [comment]
Hi, can you provide how to use this on webpack?

**Comment by tonyfromundefined** [comment]
@demian85 is this solved? I have a same problem

**Comment by tonyfromundefined** [comment]
https://webpack.js.org/configuration/output/#outputdevtoolmodulefilenametemplate

here is the solution

**Comment by LinusU** [comment]
Thanks @tonyfromundefined, that's great!

**Comment by demian85** [comment]
So the fix is to remove the `webpack://` thing then? why is it there
anyway? Can I just leave '[namespace]/[resource-path]?[loaders]'?

**Comment by LinusU** [comment]
I think that the source maps says `webpack://` so I'm not really sure that it would be correct to remove it?

What do you want it to say? `/var/task/src/main.ts` or `webpack:/src/main.ts`? 🤔

**Comment by tonyfromundefined** [comment]
If your webpack build environment is the same as your Node.js running environment (usually at development time), you can provide `[absolute-resource-path]` with the `devtoolModuleFilenameTemplate` option.

If it is different (using CI/CD), it is better to use relative paths. (ex: `../[resource-path]`)

**Comment by fronterior** [comment]
```ts
// webpack.config.ts
const projectRootDir = path.resolve(); // Root directory of project, need to be modified if necessary
const dotPaths = projectRootDir.split('/').map(() => '..').join('/'); // ../../../..

...
  output: {
    path: path.resolve(rootDir, 'dist/main'),
    devtoolModuleFilenameTemplate: `${dotPaths}/../../[resource-path]`, // '..' is required as many folders as entered in output.path
  }
...
```
In this way, I was able to create a clickable path in the VSCode terminal without 'webpack:' path.
