### ISSUE TITLE
Feature Request: Provide a `source-map-support/register-hook-require` entry-point.

### ISSUE THREAD

**Issue by coreyfarrell** [evanw/node-source-map-support#239]
I'm looking into an nyc bug report where the user cannot get source-map-support working.  Unfortunately `nyc --require source-map-support/register` does not work due to inline source-maps.  It would be very useful to us if your package included a `register-hook-require.js` (or similar file) containing:
```js
require('./').install({hookRequire: true});
```

This would give us a simple method of documenting how to enable source-map-support when not using `@babel/register`.

CC @bcoe

**Comment by LinusU** [comment]
@coreyfarrell we have added this in #257, but it isn't currently documented. Would you be able to submit a PR that adds some documentation to the readme? ❤️
