### ISSUE TITLE
How to use this in typescript with webpack?

### ISSUE THREAD

**Issue by buaazhangfan** [evanw/node-source-map-support#251]
Hi, I am using .ts with webpack to develop the core api of a mobile app and want to record error.stack into specific files. I tried to use this on webpack but it seems do not working. The error.stack is still showing xxlib.js instead of xx.ts.

Could anyone tell me how to correctly use this library with webpack and typescript?

**Comment by jmakeig** [comment]
Similar to lorenzofox3/zora#48.

**Comment by fullofcaffeine** [comment]
+1, also compiling ts through webpack using babel (for SSR), and I can't get it to work :(

**Comment by buaazhangfan** [comment]
Sorry for not closing this. I finally realized that it is the issue with webAssembly instead of webpack. I was testing it in IOS simulator while it didn't support the webAssembly. It went well after I tested it on the real device.
