### ISSUE TITLE
0.5.17 drops support for node 10 and webpack

### ISSUE THREAD

**Issue by vsumner** [evanw/node-source-map-support#270]
The latest version `0.5.17` has a [breaking change](https://github.com/evanw/node-source-map-support/pull/269) for consumers who use webpack and are on node v10.x.

I've solved this by locking my version to `0.5.16`.
```
Error: ./node_modules/source-map-support/source-map-support.js
--
  | Module not found: Error: Can't resolve 'worker_threads' in '.../node_modules/source-map-support'
  | resolve 'worker_threads' in '.../node_modules/source-map-support'
  | Parsed request is a module
```

**Comment by LinusU** [comment]
Hmm, this is interesting, the `require` is made dynamically and is inside a `try`/`catch` 🤔 

Any ideas if there is anything we can do to tell WebPack that it doesn't need to be able to resolve it?

**Comment by LinusU** [comment]
Hmm, this is probably the best solution:

https://github.com/getsentry/sentry-javascript/blob/bd35d7364191ebed994fb132ff31031117c1823f/packages/utils/src/misc.ts#L9-L11
https://github.com/getsentry/sentry-javascript/blob/89bca28994a0eaab9bc784841872b12a1f4a875c/packages/hub/src/hub.ts#L340

ref: https://github.com/webpack/webpack/issues/8826

**Comment by LinusU** [comment]
@vsumner hmm, are you using WebPack to produce a bundle for Node.js or for the browser? 🤔

**Comment by LinusU** [comment]
@vsumner could you test if #271 fixes this for you?

**Comment by vsumner** [comment]
Sorry I missed this. @LinusU thanks for fixing this!
