### ISSUE TITLE
Fragile isInBrowser test causes failures in node when window is stubbed

### ISSUE THREAD

**Issue by SystemParadox** [evanw/node-source-map-support#30]
The `isInBrowser` test is too fragile and will break if anyone defines a global window object. This can happen when implementing other compatibility shims or for testing with jsdom, etc.

```
function isInBrowser() {
  return typeof window !== 'undefined';
}
```

This causes `ReferenceError: XMLHttpRequest is not defined`.

Checking against `XMLHttpRequest` would help in this specific case, but I'm still not sure of any proper convention for detecting browser vs node at runtime.

Thanks.

**Comment by evanw** [comment]
This particular issue was fixed by pull request #44. Feel free to reopen this issue if the check for XMLHttpRequest doesn't do the trick.
