### ISSUE TITLE
Application-provided "uncaughtException" handler ignored

### ISSUE THREAD

**Issue by atombender** [evanw/node-source-map-support#40]
I initially reported it [here](https://github.com/6to5/6to5/issues/746) but was told to the problem applied to this project. My test case:

```javascript
process.on('uncaughtException', function(error) {
  console.log("uncaught");
});                       
throw new Error("Argh");
```

With Node:

```
# node test.js                            
uncaught
```

With `6to5-node`:

```
# 6to5-node test.js
/tmp/test.js:6
throw new Error("Argh");
      ^
Error: Argh
[...]
```

**Comment by xjamundx** [comment]
@atombender I'm trying to get this fixed in babel

**Comment by evanw** [comment]
Does this not work?

```
require('source-map-support').install({
  handleUncaughtExceptions: false
});
```

**Comment by julien-f** [comment]
@atombender What is the status on this issue?

**Comment by atombender** [comment]
It's working for me now. I believe @xjamundx's patch fixed it.

**Comment by julien-f** [comment]
@evanw Maybe this issue could be close?

**Comment by julien-f** [comment]
I am closing this issue, feel free to reopen it if you feel your problem has not been resolved.
