### ISSUE TITLE
Stack trace not clickable in webstorm

### ISSUE THREAD

**Issue by redmagic** [evanw/node-source-map-support#51]
Hi,

I'm sure this is a tough issue and may not get priority to look into, but when i run node with source-map-support in webstorm (either from the terminal or as a run/debug configuration), the error references are not clickable to navigate to the source of the error.

**Comment by julien-f** [comment]
Could this be because the paths do not match?

Can you copy/past a trace?

**Comment by julien-f** [comment]
Maybe related to #31?

**Comment by redmagic** [comment]
Hi,

The paths seem correct.

/Users/arjengeerse/Projects/karma-typescript/zoo/Zoo.ts:18
            this._animals.push(new animals.Owl());
                         ^
TypeError: Cannot read property 'push' of null
    at new Zoo (/Users/arjengeerse/Projects/karma-typescript/zoo/Zoo.ts:18:26)
    at main (/Users/arjengeerse/Projects/karma-typescript/main.ts:32:11)
    at Object.<anonymous> (/Users/arjengeerse/Projects/karma-typescript/main.ts:34:2)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by redmagic** [comment]
require("source-map-support").install();
var animals;
(function (animals) {
    var Animal = (function () {
        function Animal() {
            this._name = 'some animal';
        }
        Object.defineProperty(Animal.prototype, "name", {
            get: function () {
                return this._name;
            },
            enumerable: true,
            configurable: true
        });
        Animal.prototype.moves = function () {
            return 'moves in some way.';
        };
        return Animal;
    })();
    animals.Animal = Animal;
})(animals || (animals = {}));
///<reference path="Animal.ts"/>
var __extends = this.__extends || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    __.prototype = b.prototype;
    d.prototype = new __();
};
var animals;
(function (animals) {
    var Elephant = (function (_super) {
        __extends(Elephant, _super);
        function Elephant() {
            _super.apply(this, arguments);
            this._name = 'Elephant';
        }
        Elephant.prototype.moves = function () {
            return 'walks on 4 legs.';
        };
        return Elephant;
    })(animals.Animal);
    animals.Elephant = Elephant;
})(animals || (animals = {}));
///<reference path="Animal.ts"/>
var animals;
(function (animals) {
    var Owl = (function (_super) {
        __extends(Owl, _super);
        function Owl() {
            _super.apply(this, arguments);
            this._name = 'Owl';
        }
        Owl.prototype.moves = function () {
            return 'flies with wings.';
        };
        return Owl;
    })(animals.Animal);
    animals.Owl = Owl;
})(animals || (animals = {}));
///<reference path="Animal.ts"/>
var animals;
(function (animals) {
    var Snake = (function (_super) {
        __extends(Snake, _super);
        function Snake() {
            _super.apply(this, arguments);
            this._name = 'Snake';
        }
        Snake.prototype.moves = function () {
            return 'slithers.';
        };
        return Snake;
    })(animals.Animal);
    animals.Snake = Snake;
})(animals || (animals = {}));
///<reference path="../animals/Animal.ts"/>
///<reference path="../animals/Elephant.ts"/>
///<reference path="../animals/Owl.ts"/>
///<reference path="../animals/Snake.ts"/>
var zoo;
(function (zoo) {
    var Zoo = (function () {
        function Zoo(name) {
            this._animals = [];
            this.name = name;
            this._animals = null;
            this._animals.push(new animals.Elephant());
            this._animals.push(new animals.Owl());
            this._animals.push(new animals.Snake());
        }
        Zoo.prototype.enter = function () {
            return 'pay for a ticket and enter the zoo.';
        };
        Object.defineProperty(Zoo.prototype, "animals", {
            get: function () {
                return this._animals;
            },
            enumerable: true,
            configurable: true
        });
        return Zoo;
    })();
    zoo.Zoo = Zoo;
})(zoo || (zoo = {}));
///<reference path="zoo/Zoo.ts"/>
var main;
(function (main) {
    var arjen, artis;
    var Person = (function () {
        function Person() {
        }
        Person.prototype.visit = function (someLocation) {
            console.log('I am visiting ' + someLocation.name + '.');
            console.log('I ' + someLocation.enter());
        };
        //TODO: discuss duck typing below with Paco
        //lookAt(items:[{name:string;moves();}]) {
        Person.prototype.lookAt = function (items) {
            items.forEach(function (item) {
                console.log('I look at ' + item.name + '.');
                console.log('It ' + item.moves());
            });
        };
        return Person;
    })();
    arjen = new Person();
    artis = new zoo.Zoo('Artis');
    arjen.visit(artis);
    arjen.lookAt(artis.animals);
})(main || (main = {}));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImFuaW1hbHMvQW5pbWFsLnRzIiwiYW5pbWFscy9FbGVwaGFudC50cyIsImFuaW1hbHMvT3dsLnRzIiwiYW5pbWFscy9TbmFrZS50cyIsInpvby9ab28udHMiLCJtYWluLnRzIl0sIm5hbWVzIjpbImFuaW1hbHMiLCJhbmltYWxzLkFuaW1hbCIsImFuaW1hbHMuQW5pbWFsLmNvbnN0cnVjdG9yIiwiYW5pbWFscy5BbmltYWwubmFtZSIsImFuaW1hbHMuQW5pbWFsLm1vdmVzIiwiYW5pbWFscy5FbGVwaGFudCIsImFuaW1hbHMuRWxlcGhhbnQuY29uc3RydWN0b3IiLCJhbmltYWxzLkVsZXBoYW50Lm1vdmVzIiwiYW5pbWFscy5Pd2wiLCJhbmltYWxzLk93bC5jb25zdHJ1Y3RvciIsImFuaW1hbHMuT3dsLm1vdmVzIiwiYW5pbWFscy5TbmFrZSIsImFuaW1hbHMuU25ha2UuY29uc3RydWN0b3IiLCJhbmltYWxzLlNuYWtlLm1vdmVzIiwiem9vIiwiem9vLlpvbyIsInpvby5ab28uY29uc3RydWN0b3IiLCJ6b28uWm9vLmVudGVyIiwiem9vLlpvby5hbmltYWxzIiwibWFpbiIsIm1haW4uUGVyc29uIiwibWFpbi5QZXJzb24uY29uc3RydWN0b3IiLCJtYWluLlBlcnNvbi52aXNpdCIsIm1haW4uUGVyc29uLmxvb2tBdCJdLCJtYXBwaW5ncyI6IkFBQUEsSUFBTyxPQUFPLENBbUJiO0FBbkJELFdBQU8sT0FBTyxFQUFDLENBQUM7SUFFWkE7UUFJSUM7WUFGQUMsVUFBS0EsR0FBVUEsYUFBYUEsQ0FBQ0E7UUFJN0JBLENBQUNBO1FBRURELHNCQUFJQSx3QkFBSUE7aUJBQVJBO2dCQUNJRSxNQUFNQSxDQUFDQSxJQUFJQSxDQUFDQSxLQUFLQSxDQUFDQTtZQUN0QkEsQ0FBQ0E7OztXQUFBRjtRQUVEQSxzQkFBS0EsR0FBTEE7WUFDSUcsTUFBTUEsQ0FBQ0Esb0JBQW9CQSxDQUFBQTtRQUMvQkEsQ0FBQ0E7UUFFTEgsYUFBQ0E7SUFBREEsQ0FoQkFELEFBZ0JDQyxJQUFBRDtJQWhCWUEsY0FBTUEsU0FnQmxCQSxDQUFBQTtBQUNMQSxDQUFDQSxFQW5CTSxPQUFPLEtBQVAsT0FBTyxRQW1CYjtBQ25CRCxnQ0FBZ0M7Ozs7Ozs7QUFFaEMsSUFBTyxPQUFPLENBVWI7QUFWRCxXQUFPLE9BQU8sRUFBQyxDQUFDO0lBRVpBO1FBQThCSyw0QkFBTUE7UUFBcENBO1lBQThCQyw4QkFBTUE7WUFFaENBLFVBQUtBLEdBQVVBLFVBQVVBLENBQUNBO1FBSzlCQSxDQUFDQTtRQUhHRCx3QkFBS0EsR0FBTEE7WUFDSUUsTUFBTUEsQ0FBQ0Esa0JBQWtCQSxDQUFBQTtRQUM3QkEsQ0FBQ0E7UUFDTEYsZUFBQ0E7SUFBREEsQ0FQQUwsQUFPQ0ssRUFQNkJMLGNBQU1BLEVBT25DQTtJQVBZQSxnQkFBUUEsV0FPcEJBLENBQUFBO0FBQ0xBLENBQUNBLEVBVk0sT0FBTyxLQUFQLE9BQU8sUUFVYjtBQ1pELGdDQUFnQztBQUVoQyxJQUFPLE9BQU8sQ0FVYjtBQVZELFdBQU8sT0FBTyxFQUFDLENBQUM7SUFFWkE7UUFBeUJRLHVCQUFNQTtRQUEvQkE7WUFBeUJDLDhCQUFNQTtZQUUzQkEsVUFBS0EsR0FBVUEsS0FBS0EsQ0FBQ0E7UUFLekJBLENBQUNBO1FBSEdELG1CQUFLQSxHQUFMQTtZQUNJRSxNQUFNQSxDQUFDQSxtQkFBbUJBLENBQUFBO1FBQzlCQSxDQUFDQTtRQUNMRixVQUFDQTtJQUFEQSxDQVBBUixBQU9DUSxFQVB3QlIsY0FBTUEsRUFPOUJBO0lBUFlBLFdBQUdBLE1BT2ZBLENBQUFBO0FBQ0xBLENBQUNBLEVBVk0sT0FBTyxLQUFQLE9BQU8sUUFVYjtBQ1pELGdDQUFnQztBQUVoQyxJQUFPLE9BQU8sQ0FVYjtBQVZELFdBQU8sT0FBTyxFQUFDLENBQUM7SUFFWkE7UUFBMkJXLHlCQUFNQTtRQUFqQ0E7WUFBMkJDLDhCQUFNQTtZQUU3QkEsVUFBS0EsR0FBVUEsT0FBT0EsQ0FBQ0E7UUFLM0JBLENBQUNBO1FBSEdELHFCQUFLQSxHQUFMQTtZQUNJRSxNQUFNQSxDQUFDQSxXQUFXQSxDQUFBQTtRQUN0QkEsQ0FBQ0E7UUFDTEYsWUFBQ0E7SUFBREEsQ0FQQVgsQUFPQ1csRUFQMEJYLGNBQU1BLEVBT2hDQTtJQVBZQSxhQUFLQSxRQU9qQkEsQ0FBQUE7QUFDTEEsQ0FBQ0EsRUFWTSxPQUFPLEtBQVAsT0FBTyxRQVViO0FDWkQsMkNBQTJDO0FBQzNDLDZDQUE2QztBQUM3Qyx3Q0FBd0M7QUFDeEMsMENBQTBDO0FBRTFDLElBQU8sR0FBRyxDQXlCVDtBQXpCRCxXQUFPLEdBQUcsRUFBQyxDQUFDO0lBRVJjO1FBS0lDLGFBQVlBLElBQUlBO1lBSFJDLGFBQVFBLEdBQW9CQSxFQUFFQSxDQUFDQTtZQUtuQ0EsSUFBSUEsQ0FBQ0EsSUFBSUEsR0FBR0EsSUFBSUEsQ0FBQ0E7WUFDN0JBLElBQUlBLENBQUNBLFFBQVFBLEdBQUdBLElBQUlBLENBQUNBO1lBQ1RBLElBQUlBLENBQUNBLFFBQVFBLENBQUNBLElBQUlBLENBQUNBLElBQUlBLE9BQU9BLENBQUNBLFFBQVFBLEVBQUVBLENBQUNBLENBQUNBO1lBQzNDQSxJQUFJQSxDQUFDQSxRQUFRQSxDQUFDQSxJQUFJQSxDQUFDQSxJQUFJQSxPQUFPQSxDQUFDQSxHQUFHQSxFQUFFQSxDQUFDQSxDQUFDQTtZQUN0Q0EsSUFBSUEsQ0FBQ0EsUUFBUUEsQ0FBQ0EsSUFBSUEsQ0FBQ0EsSUFBSUEsT0FBT0EsQ0FBQ0EsS0FBS0EsRUFBRUEsQ0FBQ0EsQ0FBQ0E7UUFDNUNBLENBQUNBO1FBRURELG1CQUFLQSxHQUFMQTtZQUNJRSxNQUFNQSxDQUFDQSxxQ0FBcUNBLENBQUFBO1FBQ2hEQSxDQUFDQTtRQUVERixzQkFBSUEsd0JBQU9BO2lCQUFYQTtnQkFFSUcsTUFBTUEsQ0FBQ0EsSUFBSUEsQ0FBQ0EsUUFBUUEsQ0FBQ0E7WUFDekJBLENBQUNBOzs7V0FBQUg7UUFDTEEsVUFBQ0E7SUFBREEsQ0F0QkFELEFBc0JDQyxJQUFBRDtJQXRCWUEsT0FBR0EsTUFzQmZBLENBQUFBO0FBQ0xBLENBQUNBLEVBekJNLEdBQUcsS0FBSCxHQUFHLFFBeUJUO0FDOUJELGlDQUFpQztBQUdqQyxJQUFPLElBQUksQ0E4QlY7QUE5QkQsV0FBTyxJQUFJLEVBQUMsQ0FBQztJQUVUSyxJQUFJQSxLQUFLQSxFQUNMQSxLQUFLQSxDQUFDQTtJQUVWQTtRQUFBQztRQWtCQUMsQ0FBQ0E7UUFoQkdELHNCQUFLQSxHQUFMQSxVQUFNQSxZQUF5Q0E7WUFFM0NFLE9BQU9BLENBQUNBLEdBQUdBLENBQUNBLGdCQUFnQkEsR0FBR0EsWUFBWUEsQ0FBQ0EsSUFBSUEsR0FBR0EsR0FBR0EsQ0FBQ0EsQ0FBQ0E7WUFDeERBLE9BQU9BLENBQUNBLEdBQUdBLENBQUNBLElBQUlBLEdBQUdBLFlBQVlBLENBQUNBLEtBQUtBLEVBQUVBLENBQUNBLENBQUNBO1FBQzdDQSxDQUFDQTtRQUVERiwyQ0FBMkNBO1FBQzNDQSwwQ0FBMENBO1FBQzFDQSx1QkFBTUEsR0FBTkEsVUFBT0EsS0FBS0E7WUFFUkcsS0FBS0EsQ0FBQ0EsT0FBT0EsQ0FBQ0EsVUFBQ0EsSUFBSUE7Z0JBRWZBLE9BQU9BLENBQUNBLEdBQUdBLENBQUNBLFlBQVlBLEdBQUVBLElBQUlBLENBQUNBLElBQUlBLEdBQUdBLEdBQUdBLENBQUNBLENBQUNBO2dCQUMzQ0EsT0FBT0EsQ0FBQ0EsR0FBR0EsQ0FBQ0EsS0FBS0EsR0FBR0EsSUFBSUEsQ0FBQ0EsS0FBS0EsRUFBRUEsQ0FBQ0EsQ0FBQ0E7WUFDdENBLENBQUNBLENBQUNBLENBQUNBO1FBQ1BBLENBQUNBO1FBQ0xILGFBQUNBO0lBQURBLENBbEJBRCxBQWtCQ0MsSUFBQUQ7SUFFREEsS0FBS0EsR0FBR0EsSUFBSUEsTUFBTUEsRUFBRUEsQ0FBQ0E7SUFDckJBLEtBQUtBLEdBQUdBLElBQUlBLEdBQUdBLENBQUNBLEdBQUdBLENBQUNBLE9BQU9BLENBQUNBLENBQUNBO0lBRTdCQSxLQUFLQSxDQUFDQSxLQUFLQSxDQUFDQSxLQUFLQSxDQUFDQSxDQUFDQTtJQUNuQkEsS0FBS0EsQ0FBQ0EsTUFBTUEsQ0FBQ0EsS0FBS0EsQ0FBQ0EsT0FBT0EsQ0FBQ0EsQ0FBQUE7QUFDL0JBLENBQUNBLEVBOUJNLElBQUksS0FBSixJQUFJLFFBOEJWIiwiZmlsZSI6InR5cGVzY3JpcHQuanMiLCJzb3VyY2VSb290IjoiL1VzZXJzL2FyamVuZ2VlcnNlL1Byb2plY3RzL2thcm1hLXR5cGVzY3JpcHQvIiwic291cmNlc0NvbnRlbnQiOlsibW9kdWxlIGFuaW1hbHMge1xuXG4gICAgZXhwb3J0IGNsYXNzIEFuaW1hbCB7XG5cbiAgICAgICAgX25hbWU6c3RyaW5nID0gJ3NvbWUgYW5pbWFsJztcblxuICAgICAgICBjb25zdHJ1Y3RvcigpIHtcblxuICAgICAgICB9XG5cbiAgICAgICAgZ2V0IG5hbWUoKTpzdHJpbmcge1xuICAgICAgICAgICAgcmV0dXJuIHRoaXMuX25hbWU7XG4gICAgICAgIH1cblxuICAgICAgICBtb3ZlcygpOnN0cmluZyB7XG4gICAgICAgICAgICByZXR1cm4gJ21vdmVzIGluIHNvbWUgd2F5LidcbiAgICAgICAgfVxuXG4gICAgfVxufSIsIi8vLzxyZWZlcmVuY2UgcGF0aD1cIkFuaW1hbC50c1wiLz5cblxubW9kdWxlIGFuaW1hbHMge1xuXG4gICAgZXhwb3J0IGNsYXNzIEVsZXBoYW50IGV4dGVuZHMgQW5pbWFsIHtcblxuICAgICAgICBfbmFtZTpzdHJpbmcgPSAnRWxlcGhhbnQnO1xuXG4gICAgICAgIG1vdmVzKCk6c3RyaW5nIHtcbiAgICAgICAgICAgIHJldHVybiAnd2Fsa3Mgb24gNCBsZWdzLidcbiAgICAgICAgfVxuICAgIH1cbn0iLCIvLy88cmVmZXJlbmNlIHBhdGg9XCJBbmltYWwudHNcIi8+XG5cbm1vZHVsZSBhbmltYWxzIHtcblxuICAgIGV4cG9ydCBjbGFzcyBPd2wgZXh0ZW5kcyBBbmltYWwge1xuXG4gICAgICAgIF9uYW1lOnN0cmluZyA9ICdPd2wnO1xuXG4gICAgICAgIG1vdmVzKCk6c3RyaW5nIHtcbiAgICAgICAgICAgIHJldHVybiAnZmxpZXMgd2l0aCB3aW5ncy4nXG4gICAgICAgIH1cbiAgICB9XG59IiwiLy8vPHJlZmVyZW5jZSBwYXRoPVwiQW5pbWFsLnRzXCIvPlxuXG5tb2R1bGUgYW5pbWFscyB7XG5cbiAgICBleHBvcnQgY2xhc3MgU25ha2UgZXh0ZW5kcyBBbmltYWwge1xuXG4gICAgICAgIF9uYW1lOnN0cmluZyA9ICdTbmFrZSc7XG5cbiAgICAgICAgbW92ZXMoKTpzdHJpbmcge1xuICAgICAgICAgICAgcmV0dXJuICdzbGl0aGVycy4nXG4gICAgICAgIH1cbiAgICB9XG59IiwiLy8vPHJlZmVyZW5jZSBwYXRoPVwiLi4vYW5pbWFscy9BbmltYWwudHNcIi8+XG4vLy88cmVmZXJlbmNlIHBhdGg9XCIuLi9hbmltYWxzL0VsZXBoYW50LnRzXCIvPlxuLy8vPHJlZmVyZW5jZSBwYXRoPVwiLi4vYW5pbWFscy9Pd2wudHNcIi8+XG4vLy88cmVmZXJlbmNlIHBhdGg9XCIuLi9hbmltYWxzL1NuYWtlLnRzXCIvPlxuXG5tb2R1bGUgem9vIHtcblxuICAgIGV4cG9ydCBjbGFzcyBab28ge1xuXG4gICAgICAgIHByaXZhdGUgX2FuaW1hbHM6YW5pbWFscy5BbmltYWxbXSA9IFtdO1xuICAgICAgICBuYW1lOnN0cmluZztcblxuICAgICAgICBjb25zdHJ1Y3RvcihuYW1lKSB7XG5cbiAgICAgICAgICAgIHRoaXMubmFtZSA9IG5hbWU7XG50aGlzLl9hbmltYWxzID0gbnVsbDtcbiAgICAgICAgICAgIHRoaXMuX2FuaW1hbHMucHVzaChuZXcgYW5pbWFscy5FbGVwaGFudCgpKTtcbiAgICAgICAgICAgIHRoaXMuX2FuaW1hbHMucHVzaChuZXcgYW5pbWFscy5Pd2woKSk7XG4gICAgICAgICAgICB0aGlzLl9hbmltYWxzLnB1c2gobmV3IGFuaW1hbHMuU25ha2UoKSk7XG4gICAgICAgIH1cblxuICAgICAgICBlbnRlcigpIHtcbiAgICAgICAgICAgIHJldHVybiAncGF5IGZvciBhIHRpY2tldCBhbmQgZW50ZXIgdGhlIHpvby4nXG4gICAgICAgIH1cblxuICAgICAgICBnZXQgYW5pbWFscygpIHtcblxuICAgICAgICAgICAgcmV0dXJuIHRoaXMuX2FuaW1hbHM7XG4gICAgICAgIH1cbiAgICB9XG59IiwiLy8vPHJlZmVyZW5jZSBwYXRoPVwiem9vL1pvby50c1wiLz5cblxuXG5tb2R1bGUgbWFpbiB7XG5cbiAgICB2YXIgYXJqZW4sXG4gICAgICAgIGFydGlzO1xuXG4gICAgY2xhc3MgUGVyc29uIHtcblxuICAgICAgICB2aXNpdChzb21lTG9jYXRpb246e25hbWU6c3RyaW5nO2VudGVyKCk6c3RyaW5nfSkge1xuXG4gICAgICAgICAgICBjb25zb2xlLmxvZygnSSBhbSB2aXNpdGluZyAnICsgc29tZUxvY2F0aW9uLm5hbWUgKyAnLicpO1xuICAgICAgICAgICAgY29uc29sZS5sb2coJ0kgJyArIHNvbWVMb2NhdGlvbi5lbnRlcigpKTtcbiAgICAgICAgfVxuXG4gICAgICAgIC8vVE9ETzogZGlzY3VzcyBkdWNrIHR5cGluZyBiZWxvdyB3aXRoIFBhY29cbiAgICAgICAgLy9sb29rQXQoaXRlbXM6W3tuYW1lOnN0cmluZzttb3ZlcygpO31dKSB7XG4gICAgICAgIGxvb2tBdChpdGVtcykge1xuXG4gICAgICAgICAgICBpdGVtcy5mb3JFYWNoKChpdGVtKSA9PiB7XG5cbiAgICAgICAgICAgICAgICBjb25zb2xlLmxvZygnSSBsb29rIGF0ICcrIGl0ZW0ubmFtZSArICcuJyk7XG4gICAgICAgICAgICAgICAgY29uc29sZS5sb2coJ0l0ICcgKyBpdGVtLm1vdmVzKCkpO1xuICAgICAgICAgICAgfSk7XG4gICAgICAgIH1cbiAgICB9XG5cbiAgICBhcmplbiA9IG5ldyBQZXJzb24oKTtcbiAgICBhcnRpcyA9IG5ldyB6b28uWm9vKCdBcnRpcycpO1xuXG4gICAgYXJqZW4udmlzaXQoYXJ0aXMpO1xuICAgIGFyamVuLmxvb2tBdChhcnRpcy5hbmltYWxzKVxufSJdfQ==

**Comment by julien-f** [comment]
Please use [Gist](https://gist.github.com/) instead of copying large texts :)

And yes, the paths look correct, I thought there could have been truncated...

Personally, I do not use WebStorm so I cannot help you, maybe you should contact them?

**Comment by julien-f** [comment]
It may be related to #37, if so, it should be fixed in the next release.

**Comment by redmagic** [comment]
Good news, thanks!

**Comment by redmagic** [comment]
Hi,

I've noticed the file paths are not correct.

The trace contains a reference to /Users/arjengeerse/Projects/karma-typescript/zoo/Zoo.ts but that should have a js folder in between: /Users/arjengeerse/Projects/karma-typescript/js/zoo/Zoo.ts

**Comment by julien-f** [comment]
Your typescript files are in `js/` directory? Not the compiled files?

**Comment by redmagic** [comment]
Yes, the typescript files are in js/ (I know, I should call it ts/ :)

**Comment by julien-f** [comment]
I hope for a release soon (this week?), we'll see if that fixes your problem.

**Comment by julien-f** [comment]
Could you retry with the latest version (0.3.1)?

**Comment by redmagic** [comment]
Alas, still the same with that version.

I've attached my project for possible testing (without node-modules)

![karma-typescript zip](https://cloud.githubusercontent.com/assets/1224765/7931997/4d80954c-0915-11e5-836a-bf2f53ae5dae.jpg)

**Comment by julien-f** [comment]
I do not think it is a bug of `source-map-support`, I get the correct result when I explicitly set the source root in the gulpfile:

```javascript
gulp.task('typescript:compile', ['cleanwork'], function () {
  return gulp.src(['js/**/*.ts'])
    .pipe(sourcemaps.init())
    .pipe(ts({
      typescript: ts15,
      target:'es5',
      sourceMap:true,
      out:'typescript.js'
    }))
    .pipe(sourcemaps.write({
      sourceRoot: __dirname + '/js'
    }))
    .pipe(gulp.dest('target/work'))
  ;
});
```

**Comment by redmagic** [comment]
Thanks for spotting that! Still not clickable in webstorm though, I'll continue the issue there.

Big thanks for tagging along with this issue!

**Comment by julien-f** [comment]
No problem, good luck.

**Comment by DrogoNevets** [comment]
did this ever get fixed?
