### ISSUE TITLE
Publish new version for register?

### ISSUE THREAD

**Issue by pspeter3** [evanw/node-source-map-support#60]

**Comment by evanw** [comment]
I'd like to but the tests aren't passing due to the new changes coming in. I now see four failing tests. @julien-f?

**Comment by julien-f** [comment]
Unfortunatly I dont have access to a computer this weekend, if you need me dit will have to wait monday.

i suspect #47 or #58.

**Comment by julien-f** [comment]
We should set up CI to avoid that in the future (will probably set up Travis CI on monday if you agree).

**Comment by pspeter3** [comment]
Pull request #47 is the cause for most of the test failures. Removing it only causes one to fail. I'm investigating more now

**Comment by pspeter3** [comment]
I added a pull request to pass the tests and will follow up with a test for #36

**Comment by pspeter3** [comment]
And now restored the behavior of #47

**Comment by pspeter3** [comment]
Now that the pull request is closed, can we push a new version?

**Comment by evanw** [comment]
I've also got some manual tests for browser-related stuff. I'm not sure if you've been running those too but it looks like the browserify test is failing due to commit b3fd2b9 by @mprobst.

**Comment by mprobst** [comment]
@evanw any more details on how it fails? `npm test` succeeds for me, but opening `index.html` doesn't. How do you run the test?

**Comment by evanw** [comment]
Sorry, that isn't obvious. Added instructions to the readme: https://github.com/evanw/node-source-map-support/blob/master/README.md#tests. They have to run over the HTTP protocol because the file protocol is hopelessly broken.

**Comment by evanw** [comment]
Just published as version 0.3.0.

**Comment by pspeter3** [comment]
The new version seems to no longer work in my code base for reading file maps

**Comment by evanw** [comment]
@pspeter3 I just merged your pull request and published 0.3.1. Does that fix your issue?
