### ISSUE TITLE
Electron, nwjs and Brackets-Shell

### ISSUE THREAD

**Issue by LinusU** [evanw/node-source-map-support#78]
Instead of detecting the browser I think that it would be better to detect a Node.js runtime since there are a number of projects that implements both.

This leads to uncaught exceptions not being fixed in Electron. Here is the offending line.

```javascript
if (installHandler && !isInBrowser()) {
  process.on('uncaughtException', handleUncaughtExceptions);
}
```

It would be better to check for the `process` object:

```javascript
if (installHandler && typeof process === 'object' && typeof process.on === 'function') {
  process.on('uncaughtException', handleUncaughtExceptions);
}
```

**Comment by julien-f** [comment]
Seems logic, do you mind doing a PR?

**Comment by LinusU** [comment]
Sure, mind having a look at all of my pull requests? :smile:

**Comment by julien-f** [comment]
I have seen them but I d'on't have the time to review them for now.

Do they passes all tests? Even those in Chrome (https://github.com/evanw/node-source-map-support#tests)?

**Comment by LinusU** [comment]
Didn't know there where manual tests :D it would be cool to automate them with maybe phantomjs!

Anyhow, I'll make sure to run them!

**Comment by julien-f** [comment]
Indeed (#80), feel free to do it if you have the time ;)
