### ISSUE TITLE
Incorrectly matches sourceMappingUrl that occurs before the end of the file

### ISSUE THREAD

**Issue by rbuckton** [evanw/node-source-map-support#83]
Given the following file:

```
var a = "//# sourceMappingURL=foo";
//# sourceMappingURL=source.js
```

The `retrieveSourceMapURL` function matches the first occurrence, rather than the last occurrence (i.e. at the end of the file).

**Comment by rbuckton** [comment]
Sorry, it looks like this was addressed in a more recent build than the one I was using.

**Comment by julien-f** [comment]
No problems, thank you for your reports :)
