### ISSUE TITLE
SourceMappingUrl RegExp is too greedy

### ISSUE THREAD

**Issue by Ravoltz** [evanw/node-source-map-support#87]
The current RegExp is too greedy and also matches code (and comments) following the //#sourceMappingUrl comment
Please see https://regex101.com/r/xZ2xJ8/1

The one used here https://github.com/thlorenz/convert-source-map/blob/master/index.js#L5 for example works perfectly.
Please see https://regex101.com/r/xZ2xJ8/2

**Comment by julien-f** [comment]
Feel free to submit a pull request with your changes and related tests :)

**Comment by vectart** [comment]
@julien-f This fix is quite important since previous regexp caused `Maximum call stack size exceeded at RegExp.exec (native) at Array.map (native)` exception and didn't allow to use breakpoints and debugger.
@Ravoltz thank you very much!

**Comment by julien-f** [comment]
@vectart The PR has been merged didn't it?

**Comment by mairatma** [comment]
Would it be possible to update the npm version to include this change? I've been having problems with this too, but can't access the fix yet since the latest version doesn't have it :)

**Comment by julien-f** [comment]
@evanw?
